name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      JIRA_URL: https://ravindradevops25.atlassian.net
      JIRA_PROJECT_KEY: SCRUM
      JIRA_ISSUE_TYPE: Bug
      SEVERITY_THRESHOLD: high

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Verify Tools
        shell: pwsh
        run: |
          Write-Output "[DEBUG] Checking tools..."
          node --version
          npm --version
          python --version
          snyk --version
          Write-Output "[DEBUG] Tools verified successfully."

      - name: Install Python Dependencies
        shell: pwsh
        run: |
          Write-Output "[DEBUG] Installing dependencies..."
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          Write-Output "[DEBUG] Dependencies installed successfully."

      - name: Snyk Auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --json > snyk-results.json || exit 0
          echo "[DEBUG] Snyk scan completed."

      - name: Parse Results and Create JIRA Ticket
        shell: pwsh
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          $results = Get-Content snyk-results.json | ConvertFrom-Json
          if ($results.vulnerabilities.Count -gt 0) {
            echo "[DEBUG] Vulnerabilities found, creating Jira ticket..."
            python tools/create_jira_issue.py `
              --jira-url $env:JIRA_URL `
              --project $env:JIRA_PROJECT_KEY `
              --issuetype $env:JIRA_ISSUE_TYPE `
              --severity $env:SEVERITY_THRESHOLD `
              --input snyk-results.json
          } else {
            echo "[DEBUG] No vulnerabilities found, skipping Jira ticket creation."
          }
